/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;
import trabalhofinal.Data;
import trabalhofinal.Repositorio;
import trabalhofinal.Usuario;

/**
 *
 * @author huryel
 */
public class Home extends javax.swing.JFrame {
    private Usuario logado;
    /**
     * Creates new form Home
     * @param logado
     */
    public Home(Usuario logado) {
        initComponents();
        
        editarDadosPanel.setVisible(true);
        treinoPanel.setVisible(false);
        this.logado = logado;
        
        nomeCompleto.setText(logado.getNomeCompleto());
        usuario.setText(logado.getNomeUsuario());
        sexo.setText(logado.getSexo());
        senha.setText(logado.getSenha());
        diaNascimento.setText(""+logado.getDataNascimento().getDia());
        mesNascimento.setText(""+logado.getDataNascimento().getMes());
        anoNascimento.setText(""+logado.getDataNascimento().getAno());
        peso.setText(""+logado.getPeso());
        altura.setText(""+logado.getAltura());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treinoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nomejLabel1 = new javax.swing.JLabel();
        nomeCompleto1 = new javax.swing.JTextField();
        usuariojLabel1 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        sexo1 = new javax.swing.JTextField();
        sexojLabel1 = new javax.swing.JLabel();
        passwordjLabel1 = new javax.swing.JLabel();
        diaNascimento1 = new javax.swing.JTextField();
        dataNascimentojLabel1 = new javax.swing.JLabel();
        senha1 = new javax.swing.JPasswordField();
        anoNascimento1 = new javax.swing.JTextField();
        mesNascimento1 = new javax.swing.JTextField();
        pesojLabel1 = new javax.swing.JLabel();
        alturajLabel1 = new javax.swing.JLabel();
        peso1 = new javax.swing.JTextField();
        altura1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        editarDadosPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nomejLabel = new javax.swing.JLabel();
        nomeCompleto = new javax.swing.JTextField();
        usuariojLabel = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        sexojLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        diaNascimento = new javax.swing.JTextField();
        dataNascimentojLabel = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        anoNascimento = new javax.swing.JTextField();
        mesNascimento = new javax.swing.JTextField();
        pesojLabel = new javax.swing.JLabel();
        alturajLabel = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        altura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        sairIconjLabel = new javax.swing.JLabel();
        logoIconjLabel = new javax.swing.JLabel();
        editarDadosjButton = new javax.swing.JButton();
        cadastroDietajButton = new javax.swing.JButton();
        cadastroRefeicaojButton = new javax.swing.JButton();
        cadastroTreinojButton = new javax.swing.JButton();
        cadastroExerciciosjButton = new javax.swing.JButton();
        registrarDiajButton = new javax.swing.JButton();
        sairTextjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        treinoPanel.setBackground(new java.awt.Color(231, 231, 231));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 90, 35));
        jLabel5.setText("----------- CADASTRO TREINO -----------");

        nomejLabel1.setText("Nome:");

        usuariojLabel1.setText("Usuário:");

        sexojLabel1.setText("Sexo:");

        passwordjLabel1.setText("Password");

        dataNascimentojLabel1.setText("Data de Nascimento:");

        pesojLabel1.setText("Peso");

        alturajLabel1.setText("Altura");

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout treinoPanelLayout = new javax.swing.GroupLayout(treinoPanel);
        treinoPanel.setLayout(treinoPanelLayout);
        treinoPanelLayout.setHorizontalGroup(
            treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treinoPanelLayout.createSequentialGroup()
                .addGroup(treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, treinoPanelLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomejLabel1)
                                .addComponent(jLabel5)))
                        .addGroup(treinoPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sexojLabel1)
                                .addComponent(usuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                                .addComponent(usuariojLabel1)
                                .addComponent(nomeCompleto1))))
                    .addGroup(treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(treinoPanelLayout.createSequentialGroup()
                            .addComponent(diaNascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(mesNascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(anoNascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(dataNascimentojLabel1)
                        .addComponent(senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordjLabel1)
                        .addComponent(pesojLabel1)
                        .addComponent(alturajLabel1)
                        .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(altura1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        treinoPanelLayout.setVerticalGroup(
            treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treinoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomejLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariojLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexojLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordjLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNascimentojLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaNascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoNascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesNascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesojLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alturajLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addContainerGap())
        );

        getContentPane().add(treinoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 530, 550));

        editarDadosPanel.setBackground(new java.awt.Color(231, 231, 231));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 90, 35));
        jLabel4.setText("-------------- EDITAR DADOS --------------");

        nomejLabel.setText("Nome:");

        usuariojLabel.setText("Usuário:");

        sexojLabel.setText("Sexo:");

        passwordjLabel.setText("Password");

        dataNascimentojLabel.setText("Data de Nascimento:");

        pesojLabel.setText("Peso");

        alturajLabel.setText("Altura");

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarDadosPanelLayout = new javax.swing.GroupLayout(editarDadosPanel);
        editarDadosPanel.setLayout(editarDadosPanelLayout);
        editarDadosPanelLayout.setHorizontalGroup(
            editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarDadosPanelLayout.createSequentialGroup()
                .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editarDadosPanelLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomejLabel)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(editarDadosPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sexojLabel)
                                .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                                .addComponent(usuariojLabel)
                                .addComponent(nomeCompleto))))
                    .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editarDadosPanelLayout.createSequentialGroup()
                            .addComponent(diaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(mesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(anoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(dataNascimentojLabel)
                        .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordjLabel)
                        .addComponent(pesojLabel)
                        .addComponent(alturajLabel)
                        .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        editarDadosPanelLayout.setVerticalGroup(
            editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarDadosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNascimentojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alturajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(editarDadosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 530, 550));

        menuPanel.setBackground(new java.awt.Color(35, 31, 32));

        sairIconjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sairIcon.png"))); // NOI18N
        sairIconjLabel.setLabelFor(menuPanel);
        sairIconjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairIconjLabelMouseClicked(evt);
            }
        });

        logoIconjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone.png"))); // NOI18N
        logoIconjLabel.setLabelFor(menuPanel);

        editarDadosjButton.setText("Editar dados");
        editarDadosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDadosjButtonActionPerformed(evt);
            }
        });

        cadastroDietajButton.setText("Cadastro de dieta");
        cadastroDietajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroDietajButtonActionPerformed(evt);
            }
        });

        cadastroRefeicaojButton.setText("Cadastro de refeição");
        cadastroRefeicaojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroRefeicaojButtonActionPerformed(evt);
            }
        });

        cadastroTreinojButton.setText("Cadastro de treino");
        cadastroTreinojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTreinojButtonActionPerformed(evt);
            }
        });

        cadastroExerciciosjButton.setText("Cadastro de exercícios");
        cadastroExerciciosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroExerciciosjButtonActionPerformed(evt);
            }
        });

        registrarDiajButton.setText("Registrar dia");
        registrarDiajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarDiajButtonActionPerformed(evt);
            }
        });

        sairTextjLabel.setBackground(new java.awt.Color(241, 90, 35));
        sairTextjLabel.setForeground(new java.awt.Color(241, 90, 35));
        sairTextjLabel.setText("Sair");
        sairTextjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairTextjLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoIconjLabel)
                .addGap(45, 45, 45))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarDadosjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroDietajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroRefeicaojButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroTreinojButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroExerciciosjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarDiajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(sairIconjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairTextjLabel)
                .addGap(82, 82, 82))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logoIconjLabel)
                .addGap(30, 30, 30)
                .addComponent(editarDadosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroDietajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroRefeicaojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroTreinojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroExerciciosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarDiajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(sairIconjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairTextjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editarDadosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDadosjButtonActionPerformed
        // TODO add your handling code here:
        editarDadosPanel.setVisible(true);
        treinoPanel.setVisible(false);
    }//GEN-LAST:event_editarDadosjButtonActionPerformed

    private void cadastroDietajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroDietajButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroDietajButtonActionPerformed

    private void cadastroRefeicaojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroRefeicaojButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroRefeicaojButtonActionPerformed

    private void cadastroTreinojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTreinojButtonActionPerformed
        // TODO add your handling code here:
        editarDadosPanel.setVisible(false);
        treinoPanel.setVisible(true);
    }//GEN-LAST:event_cadastroTreinojButtonActionPerformed

    private void cadastroExerciciosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroExerciciosjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroExerciciosjButtonActionPerformed

    private void registrarDiajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarDiajButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarDiajButtonActionPerformed

    private void sairIconjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairIconjLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saiu!.");
    }//GEN-LAST:event_sairIconjLabelMouseClicked

    private void sairTextjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairTextjLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saiu!.");
    }//GEN-LAST:event_sairTextjLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = nomeCompleto.getText();
        String user = usuario.getText();
        String sex = sexo.getText();
        String password = String.valueOf(senha.getPassword());
        
        if (name.isEmpty() || user.isEmpty() || sex.isEmpty() || password.isEmpty() || diaNascimento.getText().isEmpty() || mesNascimento.getText().isEmpty() || anoNascimento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            Repositorio rep = new Repositorio();
            rep.leUsuarios();
            
            int dayN = Integer.parseInt(diaNascimento.getText());
            int monthN = Integer.parseInt(mesNascimento.getText());
            int yearN = Integer.parseInt(anoNascimento.getText());
            float weight = Float.parseFloat(peso.getText());
            float height = Float.parseFloat(altura.getText());
            
            rep.usuarios.remove(logado.getNomeUsuario());
            
            if (!rep.usuarios.containsKey(user)){
                Usuario u = new Usuario (name, sex, user, password, new Data(dayN, monthN, yearN), weight, height);
                rep.usuarios.put(user, u);
                rep.attUsuarios();
                JOptionPane.showMessageDialog(null, "Usuario editado com sucesso!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                this.logado = u;
            }
            else {
                JOptionPane.showMessageDialog(null, "Nome de usuario já existe", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura;
    private javax.swing.JTextField altura1;
    private javax.swing.JLabel alturajLabel;
    private javax.swing.JLabel alturajLabel1;
    private javax.swing.JTextField anoNascimento;
    private javax.swing.JTextField anoNascimento1;
    private javax.swing.JButton cadastroDietajButton;
    private javax.swing.JButton cadastroExerciciosjButton;
    private javax.swing.JButton cadastroRefeicaojButton;
    private javax.swing.JButton cadastroTreinojButton;
    private javax.swing.JLabel dataNascimentojLabel;
    private javax.swing.JLabel dataNascimentojLabel1;
    private javax.swing.JTextField diaNascimento;
    private javax.swing.JTextField diaNascimento1;
    private javax.swing.JPanel editarDadosPanel;
    private javax.swing.JButton editarDadosjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logoIconjLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField mesNascimento;
    private javax.swing.JTextField mesNascimento1;
    private javax.swing.JTextField nomeCompleto;
    private javax.swing.JTextField nomeCompleto1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JLabel nomejLabel1;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JLabel passwordjLabel1;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField peso1;
    private javax.swing.JLabel pesojLabel;
    private javax.swing.JLabel pesojLabel1;
    private javax.swing.JButton registrarDiajButton;
    private javax.swing.JLabel sairIconjLabel;
    private javax.swing.JLabel sairTextjLabel;
    private javax.swing.JPasswordField senha;
    private javax.swing.JPasswordField senha1;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField sexo1;
    private javax.swing.JLabel sexojLabel;
    private javax.swing.JLabel sexojLabel1;
    private javax.swing.JPanel treinoPanel;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuario1;
    private javax.swing.JLabel usuariojLabel;
    private javax.swing.JLabel usuariojLabel1;
    // End of variables declaration//GEN-END:variables
}
