/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author huryel
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarDadosPanel = new javax.swing.JPanel();
        nomejLabel = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        usuariojLabel = new javax.swing.JLabel();
        usuariojTextField = new javax.swing.JTextField();
        sexojTextField = new javax.swing.JTextField();
        sexojLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        diajTextField = new javax.swing.JTextField();
        dataNascimentojLabel = new javax.swing.JLabel();
        passwordjPasswordField = new javax.swing.JPasswordField();
        anojTextField = new javax.swing.JTextField();
        mesjTextField = new javax.swing.JTextField();
        pesojLabel = new javax.swing.JLabel();
        alturajLabel = new javax.swing.JLabel();
        pesojTextField = new javax.swing.JTextField();
        alturajTextField = new javax.swing.JTextField();
        cadastrarjLabel = new javax.swing.JLabel();
        cadastrarTitlejLabel = new javax.swing.JLabel();
        registrarjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(35, 31, 32));
        setPreferredSize(new java.awt.Dimension(530, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarDadosPanel.setBackground(new java.awt.Color(35, 31, 32));

        nomejLabel.setBackground(new java.awt.Color(254, 254, 254));
        nomejLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        nomejLabel.setForeground(new java.awt.Color(254, 254, 254));
        nomejLabel.setText("Nome:");

        usuariojLabel.setBackground(new java.awt.Color(254, 254, 254));
        usuariojLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        usuariojLabel.setForeground(new java.awt.Color(254, 254, 254));
        usuariojLabel.setText("Usuário:");

        sexojLabel.setBackground(new java.awt.Color(254, 254, 254));
        sexojLabel.setForeground(new java.awt.Color(254, 254, 254));
        sexojLabel.setText("Sexo:");

        passwordjLabel.setBackground(new java.awt.Color(254, 254, 254));
        passwordjLabel.setForeground(new java.awt.Color(254, 254, 254));
        passwordjLabel.setText("Password");

        dataNascimentojLabel.setBackground(new java.awt.Color(254, 254, 254));
        dataNascimentojLabel.setForeground(new java.awt.Color(254, 254, 254));
        dataNascimentojLabel.setText("Data de Nascimento:");

        pesojLabel.setBackground(new java.awt.Color(254, 254, 254));
        pesojLabel.setForeground(new java.awt.Color(254, 254, 254));
        pesojLabel.setText("Peso");

        alturajLabel.setBackground(new java.awt.Color(254, 254, 254));
        alturajLabel.setForeground(new java.awt.Color(254, 254, 254));
        alturajLabel.setText("Altura");

        cadastrarjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone.png"))); // NOI18N

        cadastrarTitlejLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        cadastrarTitlejLabel.setForeground(new java.awt.Color(241, 90, 35));
        cadastrarTitlejLabel.setText("CADASTRAR");

        registrarjButton.setText("REGISTRAR");
        registrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarDadosPanelLayout = new javax.swing.GroupLayout(editarDadosPanel);
        editarDadosPanel.setLayout(editarDadosPanelLayout);
        editarDadosPanelLayout.setHorizontalGroup(
            editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarDadosPanelLayout.createSequentialGroup()
                .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarDadosPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sexojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(usuariojLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editarDadosPanelLayout.createSequentialGroup()
                                        .addComponent(nomejLabel)
                                        .addGap(398, 398, 398))
                                    .addComponent(nomejTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexojLabel)
                                    .addComponent(usuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editarDadosPanelLayout.createSequentialGroup()
                                    .addComponent(diajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(mesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(anojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dataNascimentojLabel)
                                .addComponent(passwordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordjLabel)
                                .addComponent(pesojLabel)
                                .addComponent(alturajLabel)
                                .addComponent(pesojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alturajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(editarDadosPanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editarDadosPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cadastrarjLabel))
                            .addComponent(cadastrarTitlejLabel))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarDadosPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registrarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        editarDadosPanelLayout.setVerticalGroup(
            editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarDadosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastrarjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarTitlejLabel)
                .addGap(18, 18, 18)
                .addComponent(nomejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNascimentojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(pesojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alturajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alturajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarjButton)
                .addContainerGap())
        );

        getContentPane().add(editarDadosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alturajLabel;
    private javax.swing.JTextField alturajTextField;
    private javax.swing.JTextField anojTextField;
    private javax.swing.JLabel cadastrarTitlejLabel;
    private javax.swing.JLabel cadastrarjLabel;
    private javax.swing.JLabel dataNascimentojLabel;
    private javax.swing.JTextField diajTextField;
    private javax.swing.JPanel editarDadosPanel;
    private javax.swing.JTextField mesjTextField;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JPasswordField passwordjPasswordField;
    private javax.swing.JLabel pesojLabel;
    private javax.swing.JTextField pesojTextField;
    private javax.swing.JButton registrarjButton;
    private javax.swing.JLabel sexojLabel;
    private javax.swing.JTextField sexojTextField;
    private javax.swing.JLabel usuariojLabel;
    private javax.swing.JTextField usuariojTextField;
    // End of variables declaration//GEN-END:variables
}
